# Site settings
title: "Alberto Gálvez Gálvez"
description: "Un estudiante de programación, con mucha vocación y una gran pasión. Aprender día a día como forma de vida."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_name:                    "Alberto Gálvez Gálvez"
resume_title:                   "Desarrollador web"

resume_contact_email:           "albertogg023@gmail.com"
resume_header_intro: "Un estudiante de programación, con mucha vocación y gran pasión. Aprender día a día como forma de vida."

resume_social_links:
  resume_github_url:            "https://github.com/albertogg023"
  resume_instagram_url:         "https://www.instagram.com/albertogg023/"
 # resume_linkedin_url:          "https://www.linkedin.com/in/migueabellan"
